"""Exploratory Stage 12B diagnostics for the frozen semiconductor baseline.

The functions in this module are reusable research calculations.  They read
the Stage 11D/12 artifacts, but never overwrite them.  All estimates are
descriptive and all trailing characteristics and correlation peers are formed
with information dated strictly before the event.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats
import statsmodels.api as sm

from price_diffusion.baseline import build_semiconductor_factor
from price_diffusion.config import load_config
from price_diffusion.event_study import EventStudyConfig, run_event_study
from price_diffusion.events import EventDetectionConfig, detect_events
from price_diffusion.paths import PROJECT_ROOT
from price_diffusion.peers import (
    BROAD_SEMICONDUCTOR_PEERS,
    ECONOMIC_SUBSECTOR_PEERS,
    TRAILING_RETURN_SIMILARITY_PEERS,
    build_peer_membership,
)
from price_diffusion.returns import calculate_relative_abnormal_returns


PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
DIAGNOSTIC_DIR = PROJECT_ROOT / "outputs" / "research_diagnostics"
OUTCOMES = ("convergence", "peer_catchup", "initiator_reversal")
SMALL_SAMPLE_THRESHOLD = 30


@dataclass(frozen=True)
class DiagnosticInputs:
    """Frozen inputs used by every Stage 12B analysis."""

    config: Mapping[str, Any]
    security_master: pd.DataFrame
    universe_membership: pd.DataFrame
    daily_panel: pd.DataFrame
    peer_membership: pd.DataFrame
    relative_returns: pd.DataFrame
    events: pd.DataFrame
    event_panel: pd.DataFrame
    event_outcomes: pd.DataFrame


@dataclass(frozen=True)
class DiagnosticArtifacts:
    """Tables and figures generated by one complete diagnostic run."""

    tables: Mapping[str, pd.DataFrame]
    paths: Mapping[str, Path]


def load_diagnostic_inputs(
    config_path: str | Path = PROJECT_ROOT / "configs" / "final_baseline.yaml",
) -> DiagnosticInputs:
    """Load Stage 12B inputs without rebuilding or modifying the baseline."""
    config = load_config(config_path)
    membership = pd.read_csv(PROCESSED_DIR / "universe_membership.csv")
    if "reason" in membership and "exclusion_reason" not in membership:
        membership = membership.rename(columns={"reason": "exclusion_reason"})
    frames = {
        "daily_panel": pd.read_parquet(PROCESSED_DIR / "daily_panel.parquet"),
        "peer_membership": pd.read_parquet(PROCESSED_DIR / "peer_membership.parquet"),
        "relative_returns": pd.read_parquet(PROCESSED_DIR / "relative_returns.parquet"),
        "events": pd.read_parquet(PROCESSED_DIR / "events.parquet"),
        "event_panel": pd.read_parquet(PROCESSED_DIR / "event_panel.parquet"),
        "event_outcomes": pd.read_parquet(PROCESSED_DIR / "event_outcomes.parquet"),
    }
    membership["date"] = pd.to_datetime(membership["date"])
    for frame in frames.values():
        for column in ("date", "event_date", "calendar_date"):
            if column in frame:
                frame[column] = pd.to_datetime(frame[column])
    start = pd.Timestamp(config["date_range"]["start"])
    end = pd.Timestamp(config["date_range"]["end"])
    membership = membership.loc[membership["date"].between(start, end)].copy()
    frames["daily_panel"] = frames["daily_panel"].loc[
        frames["daily_panel"]["date"].between(start, end)
    ].copy()
    return DiagnosticInputs(
        config=config,
        security_master=pd.read_csv(PROCESSED_DIR / "security_master.csv"),
        universe_membership=membership,
        **frames,
    )


def _mean_ci(values: pd.Series, confidence: float = 0.95) -> tuple[float, float, float]:
    clean = values.dropna().to_numpy(dtype=float)
    if not len(clean):
        return np.nan, np.nan, np.nan
    mean = float(clean.mean())
    if len(clean) < 2:
        return mean, np.nan, np.nan
    sem = float(stats.sem(clean))
    critical = float(stats.t.ppf((1 + confidence) / 2, len(clean) - 1))
    return mean, mean - critical * sem, mean + critical * sem


def _sample_label(size: int, threshold: int = SMALL_SAMPLE_THRESHOLD) -> str:
    return "small_sample_descriptive_only" if size < threshold else "adequate_descriptive_sample"


def summarize_outcomes(
    outcomes: pd.DataFrame,
    group_columns: Sequence[str],
    *,
    confidence: float = 0.95,
    small_sample_threshold: int = SMALL_SAMPLE_THRESHOLD,
) -> pd.DataFrame:
    """Summarize mechanism distributions with explicit counts and labels."""
    valid = outcomes.loc[outcomes["valid_horizon"]].copy()
    rows: list[dict[str, Any]] = []
    keys: str | list[str] = list(group_columns)
    for key, group in valid.groupby(keys, dropna=False, sort=True):
        key_values = key if isinstance(key, tuple) else (key,)
        labels = dict(zip(group_columns, key_values))
        for outcome in OUTCOMES:
            values = group[outcome].dropna()
            mean, lower, upper = _mean_ci(values, confidence)
            rows.append(
                {
                    **labels,
                    "outcome": outcome,
                    "event_count": int(group["event_id"].nunique()),
                    "sample_size": int(len(values)),
                    "mean": mean,
                    "median": float(values.median()) if len(values) else np.nan,
                    "standard_deviation": float(values.std(ddof=1)) if len(values) > 1 else np.nan,
                    "minimum": float(values.min()) if len(values) else np.nan,
                    "maximum": float(values.max()) if len(values) else np.nan,
                    "proportion_positive": float(values.gt(0).mean()) if len(values) else np.nan,
                    "ci_lower": lower,
                    "ci_upper": upper,
                    "confidence_level": confidence,
                    "sample_label": _sample_label(len(values), small_sample_threshold),
                }
            )
    return pd.DataFrame(rows)


def _strictly_trailing_percentile(
    panel: pd.DataFrame,
    events: pd.DataFrame,
    value_column: str,
    *,
    window: int = 252,
    minimum_history: int = 20,
) -> pd.DataFrame:
    """Percentile of event-date values against each firm's prior observations."""
    lookups = {
        security_id: group.sort_values("date").set_index("date")[value_column]
        for security_id, group in panel.groupby("security_id", sort=False)
    }
    rows = []
    for event in events[["event_id", "date", "security_id"]].itertuples(index=False):
        series = lookups.get(event.security_id, pd.Series(dtype=float))
        history = series.loc[series.index < event.date].dropna().tail(window)
        current = series.get(event.date, np.nan)
        percentile = (
            float((history <= current).mean())
            if pd.notna(current) and len(history) >= minimum_history
            else np.nan
        )
        median = float(history.median()) if len(history) >= minimum_history else np.nan
        rows.append(
            {
                "event_id": event.event_id,
                f"{value_column}_percentile": percentile,
                f"trailing_{value_column}_median": median,
                f"{value_column}_history_count": int(len(history)),
                f"{value_column}_history_max_date": history.index.max() if len(history) else pd.NaT,
            }
        )
    return pd.DataFrame(rows)


def _peer_counts_and_coverage(inputs: DiagnosticInputs) -> pd.DataFrame:
    event_rows = inputs.events[["event_id", "date", "security_id", "subsector"]]
    observed = inputs.relative_returns[
        ["date", "security_id", "peer_definition", "peer_count", "peer_return"]
    ]
    quality = event_rows.merge(observed, on=["date", "security_id"], how="left")
    eligible = inputs.universe_membership.loc[
        inputs.universe_membership["eligible"], ["date", "security_id"]
    ].merge(
        inputs.security_master[["security_id", "subsector"]],
        on="security_id",
        how="left",
        validate="many_to_one",
    )
    possible = (
        eligible.groupby(["date", "subsector"], as_index=False)["security_id"]
        .nunique()
        .rename(columns={"security_id": "eligible_subsector_securities"})
    )
    quality = quality.merge(possible, on=["date", "subsector"], how="left")
    quality["possible_peer_count"] = quality["eligible_subsector_securities"] - 1
    quality["peer_portfolio_coverage"] = quality["peer_count"].div(
        quality["possible_peer_count"].replace(0, np.nan)
    )
    return quality[
        [
            "event_id", "peer_count", "possible_peer_count",
            "peer_portfolio_coverage", "peer_return",
        ]
    ]


def event_quality_tables(inputs: DiagnosticInputs, *, largest_n: int = 25) -> dict[str, pd.DataFrame]:
    """Build event overview, largest-event review, and concentration tables."""
    events = inputs.events.copy()
    master = inputs.security_master[["security_id", "ticker", "company_name"]]
    events = events.merge(master, on="security_id", how="left", validate="many_to_one")
    events["z_score"] = events["relative_return"] / events["relative_volatility"]
    volume = _strictly_trailing_percentile(inputs.daily_panel, events, "volume")
    peers = _peer_counts_and_coverage(inputs)
    enriched = events.merge(volume, on="event_id", how="left", validate="one_to_one").merge(
        peers, on="event_id", how="left", validate="one_to_one"
    )
    enriched["abnormal_volume_ratio"] = enriched["volume"].div(
        enriched["trailing_volume_median"].replace(0, np.nan)
    )

    rows = [{"dimension": "total", "label": "all", "event_count": events["event_id"].nunique()}]
    dimensions = {
        "year": events["date"].dt.year,
        "month": events["date"].dt.to_period("M").astype(str),
        "company": events["ticker"],
        "subsector": events["subsector"],
        "direction": events["direction"],
    }
    for dimension, labels in dimensions.items():
        counts = labels.value_counts(dropna=False).sort_index()
        rows.extend(
            {"dimension": dimension, "label": str(label), "event_count": int(count)}
            for label, count in counts.items()
        )
    summary = pd.DataFrame(rows)
    summary["event_share"] = summary["event_count"] / max(events["event_id"].nunique(), 1)

    concentration_rows: list[dict[str, Any]] = []
    for dimension, labels in dimensions.items():
        shares = labels.value_counts(normalize=True, dropna=False)
        concentration_rows.append(
            {
                "dimension": dimension,
                "category_count": int(labels.nunique(dropna=False)),
                "largest_category": str(shares.index[0]),
                "largest_category_share": float(shares.iloc[0]),
                "herfindahl_index": float(np.square(shares).sum()),
                "effective_category_count": float(1 / np.square(shares).sum()),
                "event_count": int(len(labels)),
            }
        )
    concentration = pd.DataFrame(concentration_rows)

    largest = enriched.assign(abs_relative_shock=enriched["relative_return"].abs()).sort_values(
        ["abs_relative_shock", "date"], ascending=[False, True]
    ).head(largest_n)
    largest = largest.rename(
        columns={
            "date": "event_date",
            "ticker": "initiator",
            "relative_return": "relative_shock_magnitude",
            "peer_return": "peer_return",
        }
    )
    largest["initiator_return"] = largest["relative_shock_magnitude"] + largest["peer_return"]
    largest = largest[
        [
            "event_date", "initiator", "company_name", "subsector",
            "relative_shock_magnitude", "z_score", "market_cap", "volume_percentile",
            "abnormal_volume_ratio", "peer_return", "initiator_return", "peer_count",
            "peer_portfolio_coverage",
        ]
    ]
    quality_columns = [
        "event_id", "date", "ticker", "company_name", "subsector", "direction",
        "relative_return", "z_score", "relative_volatility", "volume", "volume_percentile",
        "abnormal_volume_ratio", "market_cap", "peer_count", "possible_peer_count",
        "peer_portfolio_coverage", "volume_history_count", "volume_history_max_date",
    ]
    return {
        "event_summary": summary,
        "largest_events": largest,
        "event_concentration": concentration,
        "event_quality_detail": enriched[quality_columns],
    }


def _correlation_metrics(
    event: pd.Series,
    daily_panel: pd.DataFrame,
    peers: pd.DataFrame,
    *,
    lookback: int = 252,
    minimum_history: int = 60,
) -> dict[str, Any]:
    event_date = pd.Timestamp(event["date"])
    initiator = event["security_id"]
    peer_ids = peers["peer_id"].tolist()
    prior = daily_panel.loc[
        daily_panel["date"].lt(event_date)
        & daily_panel["security_id"].isin([initiator, *peer_ids]),
        ["date", "security_id", "return"],
    ]
    wide = prior.pivot(index="date", columns="security_id", values="return").tail(lookback)
    if initiator not in wide or not peer_ids:
        return {
            "average_peer_correlation": np.nan,
            "peer_return_similarity": np.nan,
            "correlation_history_count": 0,
            "correlation_information_max_date": pd.NaT,
        }
    individual = [wide[initiator].corr(wide[peer]) for peer in peer_ids if peer in wide]
    peer_portfolio = wide.reindex(columns=peer_ids).mean(axis=1)
    overlap = wide[initiator].notna() & peer_portfolio.notna()
    history_count = int(overlap.sum())
    return {
        "average_peer_correlation": (
            float(np.nanmean(individual)) if history_count >= minimum_history else np.nan
        ),
        "peer_return_similarity": (
            float(wide.loc[overlap, initiator].corr(peer_portfolio.loc[overlap]))
            if history_count >= minimum_history
            else np.nan
        ),
        "correlation_history_count": history_count,
        "correlation_information_max_date": wide.index.max() if len(wide) else pd.NaT,
    }


def peer_quality_table(
    inputs: DiagnosticInputs,
    *,
    lookback: int = 252,
    minimum_history: int = 60,
) -> pd.DataFrame:
    """Measure event-date peer breadth and strictly trailing return similarity."""
    counts = _peer_counts_and_coverage(inputs)
    rows = []
    for _, event in inputs.events.iterrows():
        event_peers = inputs.peer_membership.loc[
            inputs.peer_membership["date"].eq(event["date"])
            & inputs.peer_membership["security_id"].eq(event["security_id"])
            & inputs.peer_membership["peer_definition"].eq(event["peer_definition"])
        ]
        rows.append(
            {
                "event_id": event["event_id"],
                "event_date": event["date"],
                "security_id": event["security_id"],
                "subsector": event["subsector"],
                **_correlation_metrics(
                    event, inputs.daily_panel, event_peers,
                    lookback=lookback, minimum_history=minimum_history,
                ),
            }
        )
    result = pd.DataFrame(rows).merge(counts, on="event_id", how="left", validate="one_to_one")
    result["no_future_information_check"] = (
        result["correlation_information_max_date"].isna()
        | result["correlation_information_max_date"].lt(result["event_date"])
    )
    return result


def build_event_date_peer_definitions(
    inputs: DiagnosticInputs,
    *,
    correlation_lookback: int = 252,
    correlation_minimum_history: int = 60,
    correlation_peer_count: int = 10,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Create three peer definitions for baseline events using no future data."""
    rows: list[pd.DataFrame] = []
    audit_rows: list[dict[str, Any]] = []
    returns = inputs.daily_panel[["date", "security_id", "return"]]
    for event in inputs.events.itertuples(index=False):
        economic = inputs.peer_membership.loc[
            inputs.peer_membership["date"].eq(event.date)
            & inputs.peer_membership["security_id"].eq(event.security_id)
            & inputs.peer_membership["peer_definition"].eq(ECONOMIC_SUBSECTOR_PEERS)
        ].copy()
        if not economic.empty:
            rows.append(economic)

        eligible_ids = inputs.universe_membership.loc[
            inputs.universe_membership["date"].eq(event.date)
            & inputs.universe_membership["eligible"]
            & inputs.universe_membership["security_id"].ne(event.security_id),
            "security_id",
        ].tolist()
        if eligible_ids:
            broad = pd.DataFrame({"peer_id": eligible_ids})
            broad["date"] = event.date
            broad["security_id"] = event.security_id
            broad["peer_definition"] = BROAD_SEMICONDUCTOR_PEERS
            broad["weight"] = 1 / len(broad)
            rows.append(broad[["date", "security_id", "peer_id", "peer_definition", "weight"]])

        prior = returns.loc[
            returns["date"].lt(event.date)
            & returns["security_id"].isin([event.security_id, *eligible_ids])
        ]
        wide = prior.pivot(index="date", columns="security_id", values="return").tail(
            correlation_lookback
        )
        selected: list[str] = []
        if event.security_id in wide:
            correlations = wide.drop(columns=[event.security_id], errors="ignore").corrwith(
                wide[event.security_id], min_periods=correlation_minimum_history
            ).dropna().sort_values(ascending=False)
            selected = correlations.head(correlation_peer_count).index.tolist()
        if selected:
            correlation = pd.DataFrame({"peer_id": selected})
            correlation["date"] = event.date
            correlation["security_id"] = event.security_id
            correlation["peer_definition"] = TRAILING_RETURN_SIMILARITY_PEERS
            correlation["weight"] = 1 / len(correlation)
            rows.append(correlation[["date", "security_id", "peer_id", "peer_definition", "weight"]])
        audit_rows.append(
            {
                "event_id": event.event_id,
                "event_date": event.date,
                "correlation_peer_count": len(selected),
                "correlation_information_max_date": wide.index.max() if len(wide) else pd.NaT,
            }
        )
    memberships = pd.concat(rows, ignore_index=True).drop_duplicates(
        ["date", "security_id", "peer_id", "peer_definition"]
    )
    audit = pd.DataFrame(audit_rows)
    audit["no_future_information_check"] = (
        audit["correlation_information_max_date"].isna()
        | audit["correlation_information_max_date"].lt(audit["event_date"])
    )
    if not audit["no_future_information_check"].all():
        raise ValueError("correlation peer construction used event-date or future information")
    return memberships, audit


def _semiconductor_adjusted_returns(
    inputs: DiagnosticInputs,
    universe_membership: pd.DataFrame | None = None,
) -> pd.DataFrame:
    membership = (
        inputs.universe_membership
        if universe_membership is None
        else universe_membership
    )
    factor = build_semiconductor_factor(inputs.daily_panel, membership)
    adjusted = inputs.daily_panel[["date", "security_id", "return"]].merge(
        factor, on="date", how="left", validate="many_to_one"
    )
    adjusted["semiconductor_adjusted_return"] = (
        adjusted["return"] - adjusted["semiconductor_return"]
    )
    return adjusted


def compare_peer_definitions(
    inputs: DiagnosticInputs,
    memberships: pd.DataFrame | None = None,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Compare outcomes on a common baseline-event sample across peer definitions."""
    if memberships is None:
        memberships, audit = build_event_date_peer_definitions(inputs)
    else:
        audit = pd.DataFrame()
    adjusted = _semiconductor_adjusted_returns(inputs)
    outputs = []
    for definition in (
        ECONOMIC_SUBSECTOR_PEERS,
        TRAILING_RETURN_SIMILARITY_PEERS,
        BROAD_SEMICONDUCTOR_PEERS,
    ):
        peer_slice = memberships.loc[memberships["peer_definition"].eq(definition)]
        event_slice = inputs.events.copy()
        event_slice["peer_definition"] = definition
        study = run_event_study(
            event_slice,
            adjusted[["date", "security_id", "semiconductor_adjusted_return"]],
            peer_slice,
            inputs.config,
            return_column="semiconductor_adjusted_return",
            return_specification="semiconductor_adjusted_return",
        )
        outputs.append(study.outcomes)
    combined = pd.concat(outputs, ignore_index=True)
    return summarize_outcomes(combined, ["peer_definition", "horizon"]), audit


def subsector_results(inputs: DiagnosticInputs) -> pd.DataFrame:
    """Describe all three mechanisms by subsector and horizon."""
    return summarize_outcomes(inputs.event_outcomes, ["subsector", "horizon"])


def _event_characteristics(inputs: DiagnosticInputs, peer_quality: pd.DataFrame) -> pd.DataFrame:
    events = inputs.events.copy()
    events["shock_magnitude"] = events["relative_return"].abs()
    events["standardized_shock"] = events["relative_return"].abs() / events["relative_volatility"]
    events["negative_event"] = events["direction"].eq("negative").astype(float)
    volume = _strictly_trailing_percentile(inputs.daily_panel, events, "volume")
    events = events.merge(volume, on="event_id", how="left", validate="one_to_one")
    events["abnormal_volume_ratio"] = events["volume"].div(
        events["trailing_volume_median"].replace(0, np.nan)
    )

    panel = inputs.daily_panel.sort_values(["security_id", "date"]).copy()
    panel["dollar_volume"] = panel["adj_close"] * panel["volume"]
    panel["log_trailing_dollar_volume"] = np.log1p(
        panel.groupby("security_id")["dollar_volume"].transform(
            lambda values: values.shift(1).rolling(20, min_periods=10).median()
        )
    )
    events = events.merge(
        panel[["date", "security_id", "log_trailing_dollar_volume"]],
        on=["date", "security_id"], how="left", validate="one_to_one",
    )

    factor = build_semiconductor_factor(inputs.daily_panel, inputs.universe_membership).sort_values("date")
    factor["semiconductor_volatility"] = factor["semiconductor_return"].shift(1).rolling(
        20, min_periods=10
    ).std(ddof=1) * np.sqrt(252)
    factor["trailing_semiconductor_return"] = factor["semiconductor_return"].shift(1).rolling(
        126, min_periods=60
    ).sum()
    factor["bear_regime"] = factor["trailing_semiconductor_return"].lt(0).astype(float)
    events = events.merge(
        factor[["date", "semiconductor_volatility", "trailing_semiconductor_return", "bear_regime"]],
        on="date", how="left", validate="many_to_one",
    )
    events = events.merge(
        peer_quality[["event_id", "peer_count", "average_peer_correlation", "peer_return_similarity", "peer_portfolio_coverage"]],
        on="event_id", how="left", validate="one_to_one",
    )
    # Market capitalization and broad-market volatility are unavailable in the
    # frozen data. Keep explicit missing columns so coverage is auditable.
    events["log_market_cap"] = np.log(events["market_cap"].where(events["market_cap"].gt(0)))
    events["market_volatility"] = np.nan
    return events


def characteristic_relationships(
    inputs: DiagnosticInputs,
    peer_quality: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Estimate exploratory continuous relationships with HC3 uncertainty."""
    characteristics = _event_characteristics(inputs, peer_quality)
    analysis = inputs.event_outcomes.loc[inputs.event_outcomes["valid_horizon"]].merge(
        characteristics, on="event_id", how="left", suffixes=("", "_event"), validate="many_to_one"
    )
    predictors = (
        "shock_magnitude", "standardized_shock", "log_market_cap",
        "log_trailing_dollar_volume", "volume_percentile", "abnormal_volume_ratio",
        "semiconductor_volatility", "market_volatility", "trailing_semiconductor_return",
        "bear_regime", "negative_event", "peer_count", "average_peer_correlation",
        "peer_return_similarity", "peer_portfolio_coverage",
    )
    rows: list[dict[str, Any]] = []
    for horizon in sorted(analysis["horizon"].unique()):
        horizon_frame = analysis.loc[analysis["horizon"].eq(horizon)]
        for outcome in OUTCOMES:
            for predictor in predictors:
                sample = horizon_frame[[outcome, predictor]].dropna()
                row = {
                    "horizon": int(horizon), "outcome": outcome, "predictor": predictor,
                    "sample_size": int(len(sample)),
                    "coverage": float(len(sample) / max(len(horizon_frame), 1)),
                    "sample_label": _sample_label(len(sample)),
                    "coefficient_per_1sd": np.nan, "standard_error_hc3": np.nan,
                    "ci_lower": np.nan, "ci_upper": np.nan, "p_value_exploratory": np.nan,
                    "status": "insufficient_data",
                }
                if len(sample) >= 20 and sample[predictor].nunique() > 1:
                    scale = float(sample[predictor].std(ddof=1))
                    x = (sample[predictor] - sample[predictor].mean()) / scale
                    model = sm.OLS(sample[outcome], sm.add_constant(x)).fit(cov_type="HC3")
                    interval = model.conf_int(alpha=0.05).loc[predictor]
                    row.update(
                        {
                            "coefficient_per_1sd": float(model.params[predictor]),
                            "standard_error_hc3": float(model.bse[predictor]),
                            "ci_lower": float(interval.iloc[0]),
                            "ci_upper": float(interval.iloc[1]),
                            "p_value_exploratory": float(model.pvalues[predictor]),
                            "status": "estimated_exploratory",
                        }
                    )
                rows.append(row)
    return pd.DataFrame(rows), characteristics


def _candidate_frame(
    relative: pd.DataFrame,
    daily_panel: pd.DataFrame,
    security_master: pd.DataFrame,
) -> pd.DataFrame:
    candidates = relative.merge(
        security_master[["security_id", "subsector"]],
        on="security_id", how="left", validate="many_to_one",
    ).merge(
        daily_panel[["date", "security_id", "volume", "extreme_return_flag"]],
        on=["date", "security_id"], how="left", validate="one_to_one",
    )
    candidates["peer_group"] = candidates["subsector"]
    candidates["corporate_action_type"] = np.where(
        candidates["extreme_return_flag"].fillna(False), "unknown", "none"
    )
    candidates["earnings_flag"] = False
    candidates["news_identified_flag"] = False
    candidates["market_cap"] = np.nan
    return candidates


def _outcome_spec_rows(
    outcomes: pd.DataFrame,
    *,
    variation_type: str,
    specification: str,
    notes: str = "",
) -> pd.DataFrame:
    summary = summarize_outcomes(outcomes, ["horizon"])
    if summary.empty:
        return pd.DataFrame(
            [{
                "variation_type": variation_type, "specification": specification,
                "horizon": np.nan, "outcome": "convergence", "event_count": 0,
                "sample_size": 0, "mean": np.nan, "median": np.nan,
                "ci_lower": np.nan, "ci_upper": np.nan,
                "sample_label": _sample_label(0), "status": "no_valid_events", "notes": notes,
            }]
        )
    keep = [
        "horizon", "outcome", "event_count", "sample_size", "mean", "median",
        "ci_lower", "ci_upper", "sample_label",
    ]
    result = summary[keep].copy()
    result.insert(0, "specification", specification)
    result.insert(0, "variation_type", variation_type)
    result["status"] = "estimated_exploratory"
    result["notes"] = notes
    return result


def _run_detected_specification(
    inputs: DiagnosticInputs,
    membership: pd.DataFrame,
    detection: EventDetectionConfig,
    horizons: Iterable[int],
    *,
    return_column: str = "semiconductor_adjusted_return",
    return_specification: str = "semiconductor_adjusted_return",
    factor_membership: pd.DataFrame | None = None,
) -> pd.DataFrame:
    adjusted = _semiconductor_adjusted_returns(inputs, factor_membership)
    relative = calculate_relative_abnormal_returns(
        adjusted[["date", "security_id", "semiconductor_adjusted_return"]],
        membership,
        abnormal_return_column="semiconductor_adjusted_return",
    )
    candidates = _candidate_frame(relative, inputs.daily_panel, inputs.security_master)
    events = detect_events(candidates, detection)
    event_config = EventStudyConfig(
        primary_horizons=tuple(sorted(set(int(value) for value in horizons))),
        descriptive_horizons=(), pre_event_days=5,
        post_event_days=max(int(value) for value in horizons),
    )
    return run_event_study(
        events,
        adjusted[["date", "security_id", return_column]],
        membership,
        event_config,
        return_column=return_column,
        return_specification=return_specification,
    ).outcomes


def robustness_specifications(inputs: DiagnosticInputs) -> pd.DataFrame:
    """Run one-at-a-time exploratory robustness checks around the baseline."""
    rows: list[pd.DataFrame] = []
    baseline_detection = EventDetectionConfig.from_mapping(inputs.config)
    horizons = (1, 3, 5, 10, 20)

    for threshold in (2.0, 2.5, 3.0, 4.0):
        detection = EventDetectionConfig(
            minimum_relative_move=baseline_detection.minimum_relative_move,
            volatility_window=baseline_detection.volatility_window,
            threshold_multiplier=threshold,
            cooldown_period=baseline_detection.cooldown_period,
            minimum_peer_count=baseline_detection.minimum_peer_count,
            minimum_history_requirement=baseline_detection.minimum_history_requirement,
            cooldown_scope=baseline_detection.cooldown_scope,
            exclude_corporate_action_types=baseline_detection.exclude_corporate_action_types,
        )
        outcomes = _run_detected_specification(
            inputs, inputs.peer_membership, detection, horizons
        )
        rows.append(_outcome_spec_rows(
            outcomes, variation_type="event_threshold",
            specification=f"{threshold:g}_sigma",
            notes="minimum absolute move remains 5%; all other rules frozen",
        ))

    # Same frozen events: isolate the effect of horizon and return measurement.
    adjusted = _semiconductor_adjusted_returns(inputs)
    horizon_config = EventStudyConfig(
        primary_horizons=horizons, descriptive_horizons=(), pre_event_days=5, post_event_days=20
    )
    for column, label in (
        ("return", "raw_returns"),
        ("semiconductor_adjusted_return", "semiconductor_factor_adjusted"),
    ):
        study = run_event_study(
            inputs.events,
            adjusted[["date", "security_id", column]],
            inputs.peer_membership,
            horizon_config,
            return_column=column,
            return_specification=label,
        )
        rows.append(_outcome_spec_rows(
            study.outcomes, variation_type="return_definition", specification=label,
            notes="common frozen baseline event sample",
        ))
    unavailable = pd.DataFrame(
        [{
            "variation_type": "return_definition", "specification": "market_adjusted",
            "horizon": horizon, "outcome": outcome, "event_count": 0, "sample_size": 0,
            "mean": np.nan, "median": np.nan, "ci_lower": np.nan, "ci_upper": np.nan,
            "sample_label": _sample_label(0), "status": "unavailable",
            "notes": "no broad-market benchmark exists in the frozen Stage 11D dataset",
        } for horizon in horizons for outcome in OUTCOMES]
    )
    rows.append(unavailable)

    # Core baseline plus the pre-existing point-in-time extension eligibility.
    for label, eligibility_column in (
        ("core", "eligible"), ("core_plus_extension", "extension_eligible")
    ):
        membership = inputs.universe_membership.copy()
        membership["eligible"] = membership[eligibility_column].astype(bool)
        peer_classification = inputs.security_master[["security_id", "subsector"]].copy()
        peer_classification["peer_group"] = peer_classification["subsector"]
        peer_classification["classification_notes"] = "reviewed Stage 11A subsector"
        semiconductor = inputs.security_master[
            ["security_id", "ticker", "company_name", "subsector"]
        ].copy()
        semiconductor["classification_notes"] = "reviewed Stage 11A subsector"
        peer_membership = build_peer_membership(
            inputs.security_master, semiconductor, membership, peer_classification,
            definitions=(ECONOMIC_SUBSECTOR_PEERS,),
        )
        outcomes = _run_detected_specification(
            inputs, peer_membership, baseline_detection, horizons,
            factor_membership=membership,
        )
        rows.append(_outcome_spec_rows(
            outcomes, variation_type="universe", specification=label,
            notes="uses point-in-time Stage 11D eligibility flags",
        ))
    rows.append(_outcome_spec_rows(
        _run_detected_specification(
            inputs, inputs.peer_membership, baseline_detection, horizons
        ),
        variation_type="universe", specification="excluding_questionable",
        notes="identical to core: reviewed universe contains zero questionable securities",
    ))

    all_outcomes = inputs.event_outcomes.copy()
    rows.append(_outcome_spec_rows(
        all_outcomes, variation_type="extreme_event_treatment", specification="all_events"
    ))
    winsorized = all_outcomes.copy()
    flagged = all_outcomes.copy()
    flagged["valid_horizon"] = flagged["valid_horizon"].astype(bool)
    for (_, _), index in all_outcomes.loc[all_outcomes["valid_horizon"]].groupby(
        ["horizon", "return_specification"]
    ).groups.items():
        for outcome in OUTCOMES:
            values = all_outcomes.loc[index, outcome]
            lower, upper = values.quantile([0.01, 0.99])
            winsorized.loc[index, outcome] = values.clip(lower, upper)
            q1, q3 = values.quantile([0.25, 0.75])
            iqr = q3 - q1
            extreme = values.lt(q1 - 3 * iqr) | values.gt(q3 + 3 * iqr)
            if outcome == "convergence":
                flagged.loc[index[extreme], "valid_horizon"] = False
    rows.append(_outcome_spec_rows(
        winsorized, variation_type="extreme_event_treatment", specification="winsorized_1_99",
        notes="outcomes winsorized within horizon",
    ))
    rows.append(_outcome_spec_rows(
        flagged, variation_type="extreme_event_treatment", specification="exclude_flagged_extremes",
        notes="excludes convergence outside three IQRs within horizon",
    ))
    return pd.concat(rows, ignore_index=True)


def _save_figure(figure: plt.Figure, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    figure.tight_layout()
    figure.savefig(path, dpi=180, bbox_inches="tight")
    plt.close(figure)
    return path


def _plot_event_quality(tables: Mapping[str, pd.DataFrame], directory: Path) -> dict[str, Path]:
    summary = tables["event_summary"]
    year = summary.loc[summary["dimension"].eq("year")]
    figure, axis = plt.subplots(figsize=(9, 4.8))
    axis.plot(year["label"], year["event_count"], marker="o")
    axis.set(title="Detected event frequency by year", xlabel="Year", ylabel="Event count")
    axis.tick_params(axis="x", rotation=45)
    paths = {"event_frequency_over_time": _save_figure(figure, directory / "event_frequency_over_time.png")}

    quality = tables["event_quality_detail"]
    figure, axis = plt.subplots(figsize=(8, 4.8))
    axis.hist(quality["relative_return"].abs(), bins=25, color="#2563eb", alpha=0.8)
    axis.set(title="Absolute peer-relative shock magnitude", xlabel="Absolute return", ylabel="Events")
    paths["shock_magnitude_distribution"] = _save_figure(figure, directory / "shock_magnitude_distribution.png")

    subsector = summary.loc[summary["dimension"].eq("subsector")].sort_values("event_count")
    figure, axis = plt.subplots(figsize=(9, 5))
    axis.barh(subsector["label"], subsector["event_count"], color="#0f766e")
    axis.set(title="Events by subsector", xlabel="Event count", ylabel="Subsector")
    paths["events_by_subsector"] = _save_figure(figure, directory / "events_by_subsector.png")
    return paths


def _plot_peer_analysis(
    subsector: pd.DataFrame,
    quality_with_outcomes: pd.DataFrame,
    directory: Path,
) -> dict[str, Path]:
    selected = subsector.loc[
        subsector["outcome"].eq("convergence") & subsector["horizon"].eq(5)
    ].sort_values("mean")
    figure, axis = plt.subplots(figsize=(9, 5))
    errors = np.vstack([selected["mean"] - selected["ci_lower"], selected["ci_upper"] - selected["mean"]])
    axis.errorbar(selected["mean"], selected["subsector"], xerr=errors, fmt="o", color="#7c3aed")
    axis.axvline(0, color="black", linewidth=0.8)
    axis.set(title="Five-day convergence by subsector (descriptive 95% CIs)", xlabel="Mean convergence", ylabel="Subsector")
    paths = {"convergence_by_subsector": _save_figure(figure, directory / "convergence_by_subsector.png")}

    figure, axis = plt.subplots(figsize=(7.5, 5))
    sample = quality_with_outcomes.dropna(subset=["peer_return_similarity", "convergence"])
    axis.scatter(sample["peer_return_similarity"], sample["convergence"], alpha=0.45, s=22)
    if len(sample) >= 2:
        slope, intercept = np.polyfit(sample["peer_return_similarity"], sample["convergence"], 1)
        x = np.linspace(sample["peer_return_similarity"].min(), sample["peer_return_similarity"].max(), 100)
        axis.plot(x, intercept + slope * x, color="#dc2626")
    axis.axhline(0, color="black", linewidth=0.7)
    axis.set(title="Pre-event peer similarity and five-day convergence", xlabel="Trailing initiator–peer correlation", ylabel="Convergence")
    paths["peer_similarity_vs_convergence"] = _save_figure(figure, directory / "peer_similarity_vs_convergence.png")
    return paths


def _plot_characteristics(characteristics: pd.DataFrame, outcomes: pd.DataFrame, directory: Path) -> dict[str, Path]:
    sample = outcomes.loc[outcomes["valid_horizon"] & outcomes["horizon"].eq(5), ["event_id", "convergence"]].merge(
        characteristics, on="event_id", how="left", validate="one_to_one"
    )
    paths: dict[str, Path] = {}
    for predictor, filename, label in (
        ("shock_magnitude", "convergence_vs_shock_magnitude.png", "Absolute relative shock"),
        ("peer_return_similarity", "convergence_vs_peer_similarity.png", "Trailing peer similarity"),
    ):
        frame = sample.dropna(subset=[predictor, "convergence"])
        figure, axis = plt.subplots(figsize=(7.5, 5))
        axis.scatter(frame[predictor], frame["convergence"], alpha=0.45, s=22)
        if len(frame) >= 2 and frame[predictor].nunique() > 1:
            slope, intercept = np.polyfit(frame[predictor], frame["convergence"], 1)
            x = np.linspace(frame[predictor].min(), frame[predictor].max(), 100)
            axis.plot(x, intercept + slope * x, color="#dc2626")
        axis.axhline(0, color="black", linewidth=0.7)
        axis.set(title=f"Five-day convergence vs {label.lower()}", xlabel=label, ylabel="Convergence")
        paths[predictor] = _save_figure(figure, directory / filename)
    return paths


def _plot_specification_curve(specifications: pd.DataFrame, path: Path) -> Path:
    selected = specifications.loc[
        specifications["outcome"].eq("convergence")
        & specifications["horizon"].eq(5)
        & specifications["status"].eq("estimated_exploratory")
    ].copy()
    selected["label"] = selected["variation_type"] + ": " + selected["specification"]
    selected = selected.sort_values(["variation_type", "mean"])
    figure, axis = plt.subplots(figsize=(10, max(5, 0.32 * len(selected))))
    errors = np.vstack([selected["mean"] - selected["ci_lower"], selected["ci_upper"] - selected["mean"]])
    axis.errorbar(selected["mean"], np.arange(len(selected)), xerr=errors, fmt="o", color="#1d4ed8")
    axis.set_yticks(np.arange(len(selected)), selected["label"])
    axis.axvline(0, color="black", linewidth=0.8)
    axis.set(title="Exploratory five-day convergence specification curve", xlabel="Mean convergence (95% descriptive CI)", ylabel="Specification")
    return _save_figure(figure, path)


def _write_tables(tables: Mapping[str, pd.DataFrame], directory: Path) -> dict[str, Path]:
    directory.mkdir(parents=True, exist_ok=True)
    paths = {}
    for name, table in tables.items():
        path = directory / f"{name}.csv"
        table.to_csv(path, index=False)
        paths[name] = path
    return paths


def run_event_diagnostics(
    inputs: DiagnosticInputs | None = None,
    output_directory: str | Path = DIAGNOSTIC_DIR / "event_quality",
) -> DiagnosticArtifacts:
    inputs = inputs or load_diagnostic_inputs()
    directory = Path(output_directory)
    tables = event_quality_tables(inputs)
    required = {name: tables[name] for name in ("event_summary", "largest_events", "event_concentration")}
    paths = _write_tables(required, directory)
    paths.update(_plot_event_quality(tables, directory))
    return DiagnosticArtifacts(tables, paths)


def run_peer_analysis(
    inputs: DiagnosticInputs | None = None,
    output_directory: str | Path = DIAGNOSTIC_DIR / "peer_analysis",
) -> DiagnosticArtifacts:
    inputs = inputs or load_diagnostic_inputs()
    directory = Path(output_directory)
    quality = peer_quality_table(inputs)
    comparison, audit = compare_peer_definitions(inputs)
    subsector = subsector_results(inputs)
    quality_outcomes = quality.merge(
        inputs.event_outcomes.loc[
            inputs.event_outcomes["valid_horizon"] & inputs.event_outcomes["horizon"].eq(5),
            ["event_id", "convergence", "peer_catchup", "initiator_reversal"],
        ], on="event_id", how="left", validate="one_to_one",
    )
    tables = {
        "subsector_results": subsector,
        "peer_quality": quality_outcomes,
        "peer_definition_comparison": comparison,
        "peer_information_audit": audit,
    }
    required = {
        name: tables[name]
        for name in (
            "subsector_results", "peer_quality", "peer_definition_comparison",
            "peer_information_audit",
        )
    }
    paths = _write_tables(required, directory)
    paths.update(_plot_peer_analysis(subsector, quality_outcomes, directory))
    return DiagnosticArtifacts(tables, paths)


def run_characteristics_analysis(
    inputs: DiagnosticInputs | None = None,
    peer_quality: pd.DataFrame | None = None,
    output_directory: str | Path = DIAGNOSTIC_DIR / "event_characteristics",
) -> DiagnosticArtifacts:
    inputs = inputs or load_diagnostic_inputs()
    quality = peer_quality if peer_quality is not None else peer_quality_table(inputs)
    relationships, characteristics = characteristic_relationships(inputs, quality)
    directory = Path(output_directory)
    paths = _write_tables({"characteristic_relationships": relationships}, directory)
    paths.update(_plot_characteristics(characteristics, inputs.event_outcomes, directory))
    return DiagnosticArtifacts(
        {"characteristic_relationships": relationships, "event_characteristics": characteristics}, paths
    )


def run_robustness_exploration(
    inputs: DiagnosticInputs | None = None,
    output_directory: str | Path = DIAGNOSTIC_DIR / "robustness",
) -> DiagnosticArtifacts:
    inputs = inputs or load_diagnostic_inputs()
    specifications = robustness_specifications(inputs)
    directory = Path(output_directory)
    paths = _write_tables({"specification_comparison": specifications}, directory)
    paths["specification_curve"] = _plot_specification_curve(
        specifications, directory / "specification_curve.png"
    )
    return DiagnosticArtifacts({"specification_comparison": specifications}, paths)


def validate_stage12b(
    inputs: DiagnosticInputs,
    artifacts: Mapping[str, DiagnosticArtifacts],
) -> dict[str, bool]:
    """Validate leakage, baseline immutability assumptions, and reporting labels."""
    peer_tables = artifacts["peer_analysis"].tables
    audit = peer_tables["peer_information_audit"]
    quality = peer_tables["peer_quality"]
    summary_tables = [
        peer_tables["subsector_results"], peer_tables["peer_definition_comparison"],
        artifacts["event_characteristics"].tables["characteristic_relationships"],
        artifacts["robustness"].tables["specification_comparison"],
    ]
    checks = {
        "correlation_peers_strictly_pre_event": bool(audit["no_future_information_check"].all()),
        "peer_quality_strictly_pre_event": bool(quality["no_future_information_check"].all()),
        "all_subgroup_results_report_sample_size": all("sample_size" in table for table in summary_tables),
        "all_subgroup_results_label_small_samples": all("sample_label" in table for table in summary_tables),
        "baseline_event_count_unchanged": int(inputs.events["event_id"].nunique()) == 242,
        "conclusions_are_descriptive_by_design": True,
    }
    if not all(checks.values()):
        failed = ", ".join(name for name, passed in checks.items() if not passed)
        raise ValueError(f"Stage 12B validation failed: {failed}")
    return checks


def run_stage12b() -> tuple[Mapping[str, DiagnosticArtifacts], Mapping[str, bool]]:
    """Run all four Stage 12B analyses without changing Stage 12 artifacts."""
    inputs = load_diagnostic_inputs()
    event = run_event_diagnostics(inputs)
    peer = run_peer_analysis(inputs)
    characteristics = run_characteristics_analysis(inputs, peer.tables["peer_quality"])
    robustness = run_robustness_exploration(inputs)
    artifacts = {
        "event_quality": event,
        "peer_analysis": peer,
        "event_characteristics": characteristics,
        "robustness": robustness,
    }
    checks = validate_stage12b(inputs, artifacts)
    return artifacts, checks
